"""create all player tables with uuid pk

Revision ID: 048c73385700
Revises: 
Create Date: 2026-03-01 13:24:41.789717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048c73385700'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_profile',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('current_level_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slogan', sa.String(length=255), nullable=True),
    sa.Column('current_exp', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_achievement',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlock_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'achievement_id')
    )
    op.create_table('player_currency',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('currency_type', sa.Enum('gold', 'diamond', name='currencytype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'currency_type')
    )
    op.create_table('player_equipment',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('slot_type', sa.Enum('primary', 'secondary', 'melee', 'grenade', 'character', name='slottype'), nullable=False),
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'slot_type')
    )
    op.create_table('player_inventory',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('weapon', 'character', name='itemtype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('obtain_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'item_id', 'item_type')
    )
    op.create_table('player_selected_character',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_stats',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('normal', 'rank', name='gamemode'), nullable=False),
    sa.Column('current_point', sa.Integer(), nullable=True),
    sa.Column('total_game', sa.Integer(), nullable=False),
    sa.Column('number_games_win', sa.Integer(), nullable=False),
    sa.Column('kill', sa.Integer(), nullable=False),
    sa.Column('dead', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'mode')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('player_selected_character')
    op.drop_table('player_inventory')
    op.drop_table('player_equipment')
    op.drop_table('player_currency')
    op.drop_table('player_achievement')
    op.drop_table('player_profile')
    # ### end Alembic commands ###
