"""add player_rank table

Revision ID: 3a060410d053
Revises: 048c73385700
Create Date: 2026-03-12 21:23:05.987243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a060410d053'
down_revision: Union[str, None] = '048c73385700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_rank',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=False),
    sa.Column('current_point', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'season_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_rank')
    # ### end Alembic commands ###
