"""add player_auth player_session and is_new_player

Revision ID: ec1144b0f3d1
Revises: 3a060410d053
Create Date: 2026-03-12 22:30:33.003359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec1144b0f3d1'
down_revision: Union[str, None] = '3a060410d053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_auth',
    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Enum('google', 'apple', 'guest', name='authprovider'), nullable=False),
    sa.Column('provider_uid', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id_token_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ),
    sa.PrimaryKeyConstraint('auth_id'),
    sa.UniqueConstraint('provider', 'provider_uid', name='uq_provider_provider_uid')
    )
    op.create_table('player_session',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['auth_id'], ['player_auth.auth_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player_profile.player_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.add_column('player_profile', sa.Column('is_new_player', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_profile', 'is_new_player')
    op.drop_table('player_session')
    op.drop_table('player_auth')
    # ### end Alembic commands ###
