"""create config tables

Revision ID: 0dadd029678b
Revises: 
Create Date: 2026-02-11 21:13:53.673106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0dadd029678b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('achievement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('requirement', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('achievement_id')
    )
    op.create_table('character',
    sa.Column('character_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('character_type', sa.String(length=50), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('run_speed', sa.Float(), nullable=False),
    sa.Column('avatar_image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('level_config',
    sa.Column('level_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_exp', sa.Integer(), nullable=False),
    sa.Column('max_exp', sa.Integer(), nullable=False),
    sa.Column('reward_gold', sa.Integer(), nullable=False),
    sa.Column('reward_diamond', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('weapon',
    sa.Column('weapon_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('weapon_type', sa.String(length=50), nullable=False),
    sa.Column('damage', sa.Integer(), nullable=False),
    sa.Column('fire_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('weapon_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon')
    op.drop_table('level_config')
    op.drop_table('character')
    op.drop_table('achievement')
    # ### end Alembic commands ###
