"""add rank_config table

Revision ID: 62dfad56692c
Revises: 0dadd029678b
Create Date: 2026-03-12 21:23:03.269609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dfad56692c'
down_revision: Union[str, None] = '0dadd029678b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank_config',
    sa.Column('rank_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_point', sa.Integer(), nullable=False),
    sa.Column('max_point', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('rank_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rank_config')
    # ### end Alembic commands ###
