"""add reward_gold to match_player

Revision ID: 47ddf594ade4
Revises: 7c8de8f81e6c
Create Date: 2026-03-01 14:52:08.580573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47ddf594ade4'
down_revision: Union[str, None] = '7c8de8f81e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_player', sa.Column('reward_gold', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_player', 'reward_gold')
    # ### end Alembic commands ###
