"""create all match tables with uuid player_id

Revision ID: 7c8de8f81e6c
Revises: 
Create Date: 2026-03-01 13:24:46.966624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8de8f81e6c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('map_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('map_id')
    )
    op.create_table('mode',
    sa.Column('mode_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('mode_id')
    )
    op.create_table('match_history',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('mode_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('finished', 'abandoned', name='matchstatus'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['map.map_id'], ),
    sa.ForeignKeyConstraint(['mode_id'], ['mode.mode_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('match_player',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('kill', sa.Integer(), nullable=False),
    sa.Column('dead', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('result', sa.Enum('win', 'lose', name='matchresult'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('exp_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match_history.match_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_player')
    op.drop_table('match_history')
    op.drop_table('mode')
    op.drop_table('map')
    # ### end Alembic commands ###
