"""add season_id to match_history

Revision ID: 86b84e9318a5
Revises: 47ddf594ade4
Create Date: 2026-03-12 21:23:08.822676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b84e9318a5'
down_revision: Union[str, None] = '47ddf594ade4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_history', sa.Column('season_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_history', 'season_id')
    # ### end Alembic commands ###
