"""create_lucky_wheel_item_table

Revision ID: 5a9229c3bd7d
Revises: a8b9c0d1e2f3
Create Date: 2026-04-16 22:02:17.688305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '5a9229c3bd7d'
down_revision: Union[str, None] = 'a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reuse existing enum types (already created by shop table migration)
currencytype = ENUM('gold', 'diamond', name='currencytype', create_type=False)
itemtype = ENUM('weapon', 'character', 'item', name='itemtype', create_type=False)


def upgrade() -> None:
    op.create_table('lucky_wheel_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('wheel_type', currencytype, nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('item_type', itemtype, nullable=True),
    sa.Column('currency_reward', sa.Integer(), nullable=True),
    sa.Column('shop_price', sa.Integer(), server_default='0', nullable=False),
    sa.Column('weight', sa.Integer(), server_default='100', nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('image', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wheel_type', 'slot_index', name='uq_wheel_type_slot_index')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lucky_wheel_item')
    # ### end Alembic commands ###
