"""create shop table

Revision ID: 7b25e16a29f9
Revises: 
Create Date: 2026-02-11 21:10:23.699686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b25e16a29f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('shop_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('weapon', 'character', name='itemtype'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Enum('gold', 'diamond', name='currencytype'), nullable=False),
    sa.Column('discount', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('is_today', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('shop_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop')
    # ### end Alembic commands ###
